org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10
loom_version=1.8.13
fabric_api_version=0.116.15+1.21.1
fabric_key_binding_version=1.0.47+0af3f5a719
fabric_lifecycle_version=2.6.0+0865547519

mod_version=1.0.0
maven_group=com.dangkhoilkb17
archives_base_name=baritone-emergency-stop
